package View;

import Control.VeiculoController;
import DAO.ExceptionDAO;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author Neto Polacchini
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCadastrar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        labelMarca = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        labelCor = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        textFieldCor = new javax.swing.JTextField();
        textFieldMarca = new javax.swing.JTextField();
        textFieldModelo = new javax.swing.JTextField();
        textFieldAno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        buttonVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        labelMarca.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        labelMarca.setText("Marca:");
        getContentPane().add(labelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        labelModelo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        labelModelo.setText("Modelo:");
        getContentPane().add(labelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        labelCor.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        labelCor.setText("Cor:");
        getContentPane().add(labelCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        labelAno.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        labelAno.setText("Ano:");
        getContentPane().add(labelAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));
        getContentPane().add(textFieldCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, -1));
        getContentPane().add(textFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, -1));
        getContentPane().add(textFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, -1));
        getContentPane().add(textFieldAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Veículos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/carr.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        CadastrarVeiculo();
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    public void CadastrarVeiculo() {
        boolean sucesso;
        try {

            String marca = textFieldMarca.getText();
            String modelo = textFieldModelo.getText();
            String cor = textFieldCor.getText();
            int ano = Integer.parseInt(textFieldAno.getText());
            
            sucesso = VeiculoController.cadastrarVeiculo(ano, cor, marca, modelo);

            if (sucesso == true) {

                JOptionPane.showMessageDialog(null, "Carro cadastrado com sucesso");
            } else if (marca.length() <= 0 || cor.length() <= 0 || modelo.length() <= 0) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar carro");
            }
        } catch (ExceptionDAO | HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "error" + ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JTextField textFieldAno;
    private javax.swing.JTextField textFieldCor;
    private javax.swing.JTextField textFieldMarca;
    private javax.swing.JTextField textFieldModelo;
    // End of variables declaration//GEN-END:variables
}
